project_name: grabeni
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/grabeni
    binary: grabeni
    ldflags:
      - -s -w
      - -X github.com/yuuki/connperf/cmd.Version={{.Version}}
      - -X github.com/yuuki/connperf/cmd.Revision={{.ShortCommit}}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      386: "386"
      amd64: x86_64
release:
  prerelease: auto
